# Generated by Django 5.0rc1 on 2023-12-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('band', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('genres', models.ManyToManyField(blank=True, to='accounts.genre')),
                ('music_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.musicband')),
            ],
            options={
                'verbose_name': 'Аранжировка',
                'verbose_name_plural': 'Аранжировки',
            },
        ),
        migrations.CreateModel(
            name='MusicPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musical_part', models.FileField(upload_to='')),
                ('adaptation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.adaptation')),
                ('instrument', models.ForeignKey(default='Неизвестно', on_delete=django.db.models.deletion.SET_DEFAULT, to='equipment.typeofequipment')),
            ],
            options={
                'verbose_name': 'Партия аранжировки',
                'verbose_name_plural': 'Партии аранжировки',
            },
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100, verbose_name='Имя исполнителя, группы или коллаборация')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='original_genres', related_query_name='genre', to='accounts.genre')),
            ],
            options={
                'verbose_name': 'Оригинал произведения',
                'verbose_name_plural': 'Оригинальные произведения',
            },
        ),
        migrations.AddField(
            model_name='adaptation',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.original'),
        ),
        migrations.AddConstraint(
            model_name='musicpart',
            constraint=models.UniqueConstraint(fields=('adaptation', 'musical_part'), name='unique_musical_part'),
        ),
        migrations.AddConstraint(
            model_name='original',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_original_title_author'),
        ),
        migrations.AddConstraint(
            model_name='adaptation',
            constraint=models.UniqueConstraint(fields=('original', 'music_band', 'file'), name='unique_adaptation'),
        ),
    ]
