# Generated by Django 5.0rc1 on 2023-11-23 19:36

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
        ('equipment', '0001_initial'),
        ('filer', '0017_image__transparent'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_file', to='filer.file')),
                ('genres', models.ManyToManyField(blank=True, to='home.genre')),
                ('music_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.musicband')),
            ],
        ),
        migrations.CreateModel(
            name='MusicPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.adaptation')),
                ('instrument', models.ForeignKey(default='Неизвестно', on_delete=django.db.models.deletion.SET_DEFAULT, to='equipment.typeofequipment')),
                ('musical_parts', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_musical_part', to='filer.file')),
            ],
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100, verbose_name='Имя исполнителя, группы или коллаборация')),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='original_genres', related_query_name='genre', to='home.genre')),
            ],
        ),
        migrations.AddField(
            model_name='adaptation',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.original'),
        ),
        migrations.AddConstraint(
            model_name='musicpart',
            constraint=models.UniqueConstraint(fields=('adaptation', 'musical_parts'), name='unique_musical_part'),
        ),
        migrations.AddConstraint(
            model_name='original',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_original_title_author'),
        ),
        migrations.AddConstraint(
            model_name='adaptation',
            constraint=models.UniqueConstraint(fields=('original', 'music_band', 'file'), name='unique_adaptation'),
        ),
    ]
