# Generated by Django 4.2.7 on 2023-11-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField()),
                ('authors', models.ManyToManyField(blank=True, to='repertoire.author')),
                ('genres', models.ManyToManyField(to='repertoire.genre')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='genres',
            field=models.ManyToManyField(blank=True, to='repertoire.genre'),
        ),
    ]
