# Generated by Django 4.2.7 on 2023-11-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0003_alter_musicband_deputy_alter_musicband_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100, verbose_name='Имя исполнителя, группы или коллаборация')),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='repertoire.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Adaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('musical_parts', models.FileField(upload_to='')),
                ('genres', models.ManyToManyField(to='repertoire.genre')),
                ('music_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.musicband')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.original')),
            ],
        ),
        migrations.AddConstraint(
            model_name='original',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_original_title_author'),
        ),
        migrations.AddConstraint(
            model_name='adaptation',
            constraint=models.UniqueConstraint(fields=('original', 'music_band', 'file'), name='unique_adaptation'),
        ),
    ]
