# Generated by Django 4.2.7 on 2023-11-16 18:29

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptation',
            name='musical_parts',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musical_parts', to='filer.file'),
        ),
    ]
