# Generated by Django 4.2.7 on 2023-11-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_alter_adaptation_file_alter_adaptation_musical_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptation',
            name='genres',
            field=models.ManyToManyField(blank=True, to='repertoire.genre'),
        ),
    ]
