# Generated by Django 4.2.7 on 2023-11-15 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[(1, 'Активен'), (0, 'Списан')], default=1, max_length=5)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-register_date',),
            },
        ),
    ]
