# Generated by Django 4.2.7 on 2023-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('1', 'Активен'), ('0', 'Списан')], default='1', max_length=5),
        ),
    ]
