# Generated by Django 4.2.7 on 2023-11-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0003_alter_musicband_deputy_alter_musicband_leader_and_more'),
        ('app_auth', '0003_alter_customuser_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('music_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.musicband')),
                ('participants', models.ManyToManyField(to='app_auth.customuser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rehearsal',
            constraint=models.UniqueConstraint(fields=('music_band', 'start_date'), name='unique_rehearsal_music_band'),
        ),
    ]
