# Generated by Django 5.0rc1 on 2023-12-05 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfEquipment',
            fields=[
                ('name', models.CharField(help_text='Введите новую разновидность оборудования/инструмента', max_length=100, primary_key=True, serialize=False, verbose_name='Тип оборудования/инструмента')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудований',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(auto_created=True, help_text='Укажите дату начала активного использования оборудования/инструмента', verbose_name='Дата введения в эксплуатацию')),
                ('name', models.CharField(help_text='Введите уникальное название модели оборудования/инструмента', max_length=200, verbose_name='Название оборудования/инструмента')),
                ('state', models.BooleanField(default=True, help_text='Отметьте текущее состояние оборудования/инструмента', verbose_name='Активно/Списано оборудование')),
                ('description', models.TextField(blank=True, help_text='Опишите основные характеристики оборудования/инструмента', max_length=1000, null=True, verbose_name='Описание')),
                ('music_band_show', models.BooleanField(default=True, help_text='Укажите, стоит ли отображать ваш инструмент в списке инструментов музыкального коллектива, или нет?', verbose_name='Отображать в музыкальной группе?')),
                ('owner', models.ForeignKey(help_text='Укажите владельца данного оборудования/инструмента', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец оборудования/инструмента')),
                ('type', models.ForeignKey(help_text='Выберите тип оборудования/инструмента', on_delete=django.db.models.deletion.CASCADE, to='equipment.typeofequipment', verbose_name='Тип оборудования/инструмента')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
                'ordering': ('-register_date',),
                'get_latest_by': '-register_date',
            },
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_equipment'),
        ),
    ]
