# Generated by Django 4.2.7 on 2023-11-28 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfEquipment',
            fields=[
                ('name', models.CharField(default='Неизвестно', help_text='Введите новую разновидность оборудования/инструмента', max_length=100, primary_key=True, serialize=False, verbose_name='Тип оборудования/инструмента')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудований',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(auto_created=True, help_text='Укажите дату начала активного использования оборудования/инструмента', verbose_name='Дата введения в эксплуатацию')),
                ('name', models.CharField(help_text='Введите уникальное название модели оборудования/инструмента', max_length=200, verbose_name='Название оборудования/инструмента')),
                ('state', models.CharField(choices=[('1', 'Активен'), ('0', 'Списан')], default='1', help_text='Выберите текущее состояние оборудования/инструмента', max_length=5, verbose_name='Состояние')),
                ('description', models.TextField(blank=True, help_text='Опишите основные характеристики оборудования/инструмента', max_length=1000, null=True, verbose_name='Описание')),
                ('music_band', models.ForeignKey(blank=True, help_text='Укажите коллектив, в котором территориально находится данное оборудование/инструмент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_band', to='band.musicband', verbose_name='Музыкальная группа')),
                ('owner', models.ForeignKey(help_text='Укажите владельца данного оборудования/инструмента', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец оборудования/инструмента')),
                ('type', models.ForeignKey(default='Неизвестно', help_text='Выберите тип оборудования/инструмента', on_delete=django.db.models.deletion.SET_DEFAULT, to='equipment.typeofequipment', verbose_name='Тип оборудования/инструмента')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
                'ordering': ('-register_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_equipment'),
        ),
    ]
