# Generated by Django 4.2.7 on 2023-11-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_skills', related_query_name='skill', to='home.skills', verbose_name='Навыки'),
        ),
    ]
