# Generated by Django 4.2.7 on 2023-11-16 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_customuser_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.date(2003, 11, 17), verbose_name='Дата рождения'),
        ),
    ]
