# Generated by Django 5.0rc1 on 2023-12-13 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date(2003, 12, 14), verbose_name='Дата рождения'),
        ),
    ]
