# Generated by Django 5.0rc1 on 2023-11-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBand',
            fields=[
                ('register_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
