# Generated by Django 4.2.7 on 2023-11-15 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBand',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('register_date', models.DateField(auto_now=True)),
                ('url', models.URLField()),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
