# Generated by Django 4.2.7 on 2023-11-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicband',
            name='deputy',
            field=models.ManyToManyField(related_name='music_deputies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musicband',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicband',
            name='members',
            field=models.ManyToManyField(related_name='music_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicband',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
