# Generated by Django 4.2.7 on 2023-11-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_customuser_skills'),
        ('band', '0002_musicband_deputy_musicband_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicband',
            name='deputy',
            field=models.ManyToManyField(blank=True, related_name='music_deputies', to='app_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='musicband',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='app_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='musicband',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='music_members', to='app_auth.customuser'),
        ),
    ]
