# Generated by Django 5.0rc1 on 2023-11-23 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('6', 'Школьный'), ('5', 'Студенческий'), ('4', 'Городской'), ('3', 'Областной'), ('2', 'Федеральный'), ('1', 'Мировой')], max_length=1)),
                ('sponsor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('name', 'start_datetime'), name='unique_event'),
        ),
        migrations.AddField(
            model_name='performance',
            name='artists',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
