# Generated by Django 5.0rc1 on 2023-11-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
        ('event', '0001_initial'),
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.adaptation'),
        ),
        migrations.AddField(
            model_name='performance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='performance',
            name='music_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.musicband'),
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('event', 'composition', 'music_band'), name='unique_performance'),
        ),
    ]
