# Generated by Django 5.0rc1 on 2023-11-23 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=150, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('music_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.musicband')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='rehearsal',
            constraint=models.UniqueConstraint(fields=('music_band', 'start_date'), name='unique_rehearsal_music_band'),
        ),
    ]
