# Generated by Django 5.0rc1 on 2023-11-23 19:36

import datetime
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('birthday', models.DateField(default=datetime.date(2003, 11, 24), verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский'), ('n', 'Не определён')], default='n', max_length=1, verbose_name='Пол')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('genres', models.ManyToManyField(blank=True, default='Другое', related_name='user_genres', related_query_name='genre', to='home.genre', verbose_name='Любимые жанры')),
                ('music_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='band.musicband')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='user_skills', related_query_name='skill', to='home.skills', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
